---
title: 第六届中国养虾高手年会记录
author: Sheng Luan
date: '2018-01-27'
slug: the-sixth-meeting-about-how-to-rearing-shrimp-in-haikou
categories:
  - meeting
tags:
  - shrimp
---

1.25-26日，参加了在海口由水产前沿举办的第六届中国养虾高手年会。具体的会议记录，见水产前沿的[详细报道](http://www.fishfirst.cn/article-98482-1.html)。

第一次参加非学术组织举办的这种会议，感觉非常新鲜，也非常有活力。整个活动，没有政府部门的领导参加，纯粹是学术界跟企业界的对接，这种形式真的非常好。很多饲料、苗种企业对于真正有用的学术成果非常渴望，从科研工作者的角度来看，学术成果要想转化为生产力，应该多参加这样的会议。也有利于自己学术方向的调整，做真正有用的研究。

会议的几点收获：

## 1 种业方面

### 1.1 种质方面

* 中国南美白对虾的养殖产量下降的非常厉害。SIS郑光发先生的报道，预测2017年南美白对虾国内产量只有58万吨左右。印度和越南的产量在不断增加，大约分别为45万吨和50万吨左右。这个结果与统计年鉴存在较大的出入。
* 国外进口南美白对虾量在不断增加，正大陈丹先生的报告显示，2017年进口量在30万吨左右。
* 中国进口种虾没有充分发挥性能。中国进口25万对，印度和越南进口分别在9万对左右。结果产量现在后两个国家追平。SIS郑光发认为主要原因是进口种虾鱼龙混杂，没有严格把控亲虾来源。事实上在企业的走访中，也表明一些**进口亲虾都携带荧光弧菌**等问题。
* 国外公司如SIS在抗性测试方面，从报告中表明是对各种细菌和病毒都进行抗性测试。
* 国外公司已经意识到苗种的适应性差问题，譬如SIS提到，专门在国内开始性状测试工作，主要是针对土塘和高位池进行测试。

正大陈丹先生在报告中提到，正大优质种虾的标准：

* 没有以下病毒：WSSV（白斑综合症病毒）、IHHNV（Infectious subcutaneous and hematopoietic tissue necrosis virus，传染性皮下及造血组织坏死病毒）、IMNV(传染性肌肉坏死病毒）、TSV（桃拉病毒）、黄头病毒（YHV）、鳃病毒（GAV）、NHPB（肝胰腺坏死性细菌）、EMS/AHPND（早期死亡综合征/急性肝胰腺坏死症）、EHP；
* 养殖天数超过180d，公虾体重>65g，母虾体重70g；
* 性器官发育完好，肢体发育完全，健康活力好；
* 亲虾产的幼体从2012年的350um，到2017年的480um，大了1/3；
* 苗种的生长速度，以达到30g/尾规格为标准，2012年需要110d，2017年只需要64d，缩短了56d，非常惊人。

### 1.2 生物安保

从一个厂区的角度，一个种虾场或者苗种场应该具备：

* 进出车辆消毒
* 生产度单独隔离
* 生产区雾化消毒通道
* 人员淋浴消毒室，进出车间人员雾化消毒

黄倢老师的报告：
从他的报告中，可以看出，2013-2017，病毒的检出率是在不断下降的。特别是EHP的检出率，已经由2017年的50%多，下降到现在的不到30%。WSSV的检出率从30%到10%。急性肝胰腺坏死症2016年特别厉害（接近30%），2017在15%左右。

* 一种新的病毒病：虾血细胞虹彩病毒病（SHIV）。主要症状：
    + 肝胰腺颜色变浅
    + 额剑基部出现白点，如罗氏沼虾“白头病"
    + 整体颜色变浅，体节明显
    + 幼虾死亡明显
* 感染24小时内升温至33度可以有效的防止白斑病。
* 不支持多种虾混养，认为会带来疾病的传播。
* 急性肝胰腺坏死症
    + 机理：Pirvp毒力蛋白对幼虾消化系统急性毒性
    + 菌株：副溶血弧菌、坎贝氏弧菌、欧文氏弧菌
    + 症状：肝脏白膜减少-白膜消失-颜色变浅-黄白-灰白-透明；虾体尾单附肢发蓝、虾体发蓝、虾肉浑浊、虾体发白；幼虾死亡率高、可以达到>80%；成虾死亡率低
    + 消毒：过硫酸氢钾消毒效果差；双氧水、聚六亚甲基胍盐酸盐具有较好的作用。
    + 预防：降低盐度至6‰之下，
* EHP
    + 机理：EHP感染导致肝脏能量供应途径受阻。
    + 因为一直在摄食，肝胰腺和肠道颜色较深，但是生长缓慢，肌肉腹节透明。
    + EHP感染超过10^3拷贝/ng肝胰腺DNA，那么受感染的风险较大。
    + EHP感染会导致体重降低30%。
    + 单独感染可能并不致死，与弧菌一起感染，死亡率增加。
    + 存在不同的传播模式，单峰或者双峰，可能在不同的发育阶段都可以感染。
    
关于病原的检测：  
* 杭州众测生物科技有限公司，开发了水生动物疾病分子检测系统解决方案。利用重组介导链替换核酸扩增技术RAAD，可以5-15分钟出结果。
* DHelix 广州双螺旋基因技术有限公司，也可以快速检测病毒、细菌等病原。

## 2 配套技术
### 2.1 饲料

正大1-3号虾料，大虾宝、中虾宝，蛋白含量在40%以上。

英伟公司（INVE）推出了两种饲料：

* BREED-S FRESH 普瑞德种虾专用饲料，可以替代70%鲜活料、生物安全性高、提高产卵性能。它的营养成分：60%蛋白、Lipid（油脂）15%、n-3 HUFA 2.8%、Vit A 22500IU/kg、Vit E 500ppm、Vit c 3000ppm。在种虾饲料中添加益生菌（probiotics），产卵和孵化过程中，添加益生菌。
* FRiPPAK FRESH GOLD 金牌福瑞派系列虾苗专用微胶囊饵料。根据报告，可以替代65%-85%的卤虫。

天津英创公司推出了育苗宝1号、鱼苗宝2号：主要是桡足类营养强化后，清洗、消毒，零下30度冷冻，真空包装。如果打算替代卤虫，死掉后，虾苗是否爱吃，是个问题。

 
### 2.2 水质处理、分析和调节

参观了海兴农翁田场，育苗用水处理模式：抽水到蓄水池、一二级沙滤去除大颗粒杂质、遮光黑暗沉淀池、氯处理杀菌、沙港去除小颗粒杂质、去除有机物（蛋白分离器）、二次遮光沉淀、臭氧杀菌消毒、过滤细小颗粒吸附残余臭氧、过滤细小颗粒、紫外线杀菌、进入车间。

正大试剂盒：**余氯、亚硝酸盐、pH值、总碱度、钾盐、溶解氧、氨氮、钙镁离子**。

益生菌：水净宝、速清宝、育水宝、益菌宝、稳水宝、健肠宝

矿物质：钙镁晶、钙/镁/钾速补、塘低净、海盐宝（提高盐度）、海蜜（提高总碱度）

亚硝酸盐检测和调控是一个重点，可以多措并举：

* 高效集排污、菌、藻、交换量
* 从源头控制
* 高溶解氧缓解毒性
* 盐度千分之五的相对安全阈值
* 发挥化能自养菌-硝化细菌的功效

多位专家强调：益生菌如芽孢杆菌增值速度慢，大约3个小时，而有害菌如弧菌增值速度在20分钟。因此应该使用高品质的益生菌。

### 2.3 育苗技术

INVE 专家做了题为“The roadmap to quality shrimp fry"的报告，具体内容后续再行更新。

### 2.4 养虾模式

3C：Clean shrimp、Clean water、Clean bottom

外籍专家 M. Poulain - Project Manager 做了一个报告：Indoor zero water exchange super-intensive shrimp production 高密度零交换水工厂化对虾养殖模式。

工厂化模式下的检测参考流程：

* 水源检测：初期检测、定期检测
* 其他定期检测项目
      + 菌相
      + 理化因子：氨氮、亚硝酸盐和酸碱度
      + 虾体：健康程度、生长速度、匀称度、肥满度
      + 饲料及动保产品的定期抽检
      
养虾达人李涛报告中的两种养殖模式：

（1）换水量很少，连续3天换水量少于15%，类似于循环水养殖模式。

这种模式应该以菌为主，以藻为辅。微生物作为主要的水质处理手段。这种方法通过较高频率的补充微生物，稳定水体菌相、水体理化指标。优点：

* 料比低。
* 可复制性高。
* 稳定性强。
* 交换量低。
* 超高菌相，压制弧菌。
* 定向搭配藻种，减轻系统负担。
* 充分利用微生物的代谢产物，保健抗病。
* 受季节和光照的影响弱。

对于这种模式，曝气要均匀，密集；气盘分散型点式布局。

轻微搅动水，转水动力不能大，时间也不易过长，否则生成的絮团不沉浮在水中，虾吃不到。换水量也不宜过大，否则影响菌相和总菌量。

（2）大换水量模式

曝气：集中在外围，中间不宜放置过多的曝气头。否则影响水流动。

转水：动水力度大，转水时间长。

换水：量要大，保证水质清新。

转水排污，由于没有足够的营养物质供细菌附着，使用微生态制剂效果并不显著。

### 2.4 配套设备

有一家[鱼儿乐](http://www.yu2le.com/index.html#)公司,一家物联网平台，实现了养殖水质数据在线监控。有一套手册，有时间再仔细看一下。

目前的最新系统是鱼儿乐X5技术：荧光法溶解氧传感器；寿命长，稳定性好，免维护。
      